1. Functions to create Arrays

In [1]:
#importing numpy
import numpy as np

In [2]:
from numpy import array
l=[1.0,2.0,3.0,4.0]
a= array(l)
print (a)
print (a.shape)
print(a.dtype)
#example for creating array with array() function

[1. 2. 3. 4.]
(4,)
float64


1.1empty

In [3]:
#create empty array
from numpy import empty
a=empty([4,4])
print(a) #it prints empty array contents may vary in ecan code



[[4.65515658e-310 0.00000000e+000 2.41907520e-312 2.14321575e-312]
 [2.46151512e-312 2.31297541e-312 2.35541533e-312 2.05833592e-312]
 [2.22809558e-312 2.56761491e-312 2.48273508e-312 2.05833592e-312]
 [2.05833592e-312 2.29175545e-312 2.07955588e-312 2.14321575e-312]]


1.2 Zeros

In [4]:
#create zero array
from numpy import zeros
a = zeros([5,3]) #five row three column array zero
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


1.3 ones

In [5]:
# create one array
from numpy import ones
a = ones([5]) #1 row five column array 
print(a)

[1. 1. 1. 1. 1.]


2 combining array

2.1 vertical stack

In [6]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([3,4,5,6])
print(a1)
# create second array
a2 = array([4,5,6,7])
print(a2)
# vertical stack
a3 = vstack((a1, a2)) #takes only same dimension array 
print(a3)
print(a3.shape)

[3 4 5 6]
[4 5 6 7]
[[3 4 5 6]
 [4 5 6 7]]
(2, 4)


2.2 horizontal stack

In [7]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([[3,8,9,1],[1,2,3]]) #cant directly hstack two different shapes
print(a1)
# create second array
a2 = array([[7,5,6,1],[1,5,6]]) # this is depreciated
print(a2)
# create horizontal stack
a3 = hstack((a1, a2)) #this adds columns with each other
print(a3)
print(a3.shape)

[list([3, 8, 9, 1]) list([1, 2, 3])]
[list([7, 5, 6, 1]) list([1, 5, 6])]
[list([3, 8, 9, 1]) list([1, 2, 3]) list([7, 5, 6, 1]) list([1, 5, 6])]
(4,)


/tmp/ipykernel_6887/3669229083.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = array([[3,8,9,1],[1,2,3]]) #cant directly hstack two different shapes
/tmp/ipykernel_6887/3669229083.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = array([[7,5,6,1],[1,5,6]]) # this is depreciated


In [8]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2)) # this function adds column
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


#index slice and reshape NUMPY array



##one dimensional list to array

In [9]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55, 66, 77]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55 66 77]
<class 'numpy.ndarray'>


## Two-Dimensional List of Lists to Array

In [10]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66],
[77,88]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]
 [77 88]]
<class 'numpy.ndarray'>


## array indexing 
##one dimensional indexing

In [11]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55, 66, 77])
# index data 
print(data[0])
print(data[5])

11
66


In [12]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55, 66])
# index data
# print(data[7]) # running this give index error. can try it by  uncommenting the code

In [13]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55,66])
# index data
print(data[-2])
print(data[-5])

55
22


##two dimensional indexing

In [14]:
# index two-dimensional array
from numpy import array
# doing data[0,0] and data [0][0] are two different things
data = array([
[11, 22],
[33, 44],
[55, 66]])

print(data[0,0])
print(data[0],[0]) #it gives two different list 1st row and seperate 0 column

11
[11 22] [0]


In [15]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


##Array slicing
## one dimensional slicing

In [16]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [17]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [18]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


##Two-Dimensional Slicing

In [19]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


## train test split

In [20]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# array reshaping 

## data shape

In [21]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [22]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [24]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## reshape 1 D array to 2d arry

In [2]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([10,12,14,15,17])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


## reshape 2d t 3d array

In [7]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
#preview the shaoe of array
print(data.shape[0])
print(data.shape[1])
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
3 1
2 1
(3, 2, 1)


# Numpy array Broadcasting

### what we going to learn?
##### problem of arithmetic with arrays with different sizes
##### the solution of braodcastng and common examples in one and two    dimensions
##### the rule of array braodcasting when array fails

## limitation with array arithmetic

In [11]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
c= array([1,2,2])
print(b)
# broadcast
d = a + b
e = a + c  #can only bordcast arrya of same shape.
print(d)
print(e)

[1 2 3]
2
[3 4 5]
[2 4 5]


## scalar and two dimensional array

In [1]:
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


## one dimensional and two dimensional arrays

In [1]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


## limitation of broadcasting

In [2]:
# # broadcasting error
# from numpy import array
# # define two-dimensional array
# A = array([
# [1, 2, 3],
# [1, 2, 3]])
# print(A.shape)
# # define one-dimensional array
# b = array([1, 2])
# print(b.shape)
# # attempt broadcast
# C = A + b
# print(C)


# this code give the error cause it cant be broadcasted

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 


## Extensons

In [10]:
# arryas making on own
import numpy as np

a= np.array([[1,2,3],[5,6,7]]);
b= np.array([1,2,3])
c = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
d = np.array([
    [[1,2,3]],
    [[2,3,4]]])


a.shape, b.shape, c.shape , d.shape



# numpy array explained:
# here array of shape if two bracketes then it is tow dimensionssla rr

((2, 3), (3,), (1, 3, 3), (2, 1, 3))

In [16]:
a= np.array([
    [[1,2,3],[1,2,3],[3,4,5]],[[1,2,3],[1,2,3],[3,4,5]]
    ])
a.shape

(2, 3, 3)