1. Functions to create Arrays

In [ ]:
#importing numpy
import numpy as np

In [ ]:
from numpy import array
l=[1.0,2.0,3.0,4.0]
a= array(l)
print (a)
print (a.shape)
print(a.dtype)
#example for creating array with array() function

[1. 2. 3. 4.]
(4,)
float64


1.1empty

In [ ]:
#create empty array
from numpy import empty
a=empty([4,4])
print(a) #it prints empty array contents may vary in ecan code



[[2.83651309e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 2.95069422e+179]
 [5.92937682e-038 7.73685042e-091 2.19219402e-056]]


1.2 Zeros

In [ ]:
#create zero array
from numpy import zeros
a = zeros([5,3]) #five row three column array zero
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


1.3 ones

In [ ]:
# create one array
from numpy import ones
a = ones([5]) #1 row five column array 
print(a)

[1. 1. 1. 1. 1.]


2 combining array

2.1 vertical stack

In [ ]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([3,4,5,6])
print(a1)
# create second array
a2 = array([4,5,6,7])
print(a2)
# vertical stack
a3 = vstack((a1, a2)) #takes only same dimension array 
print(a3)
print(a3.shape)

[3 4 5 6]
[4 5 6 7]
[[3 4 5 6]
 [4 5 6 7]]
(2, 4)


2.2 horizontal stack

In [ ]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([[3,8,9,1],[1,2,3]]) #cant directly hstack two different shapes
print(a1)
# create second array
a2 = array([[7,5,6,1],[1,5,6]]) # this is depreciated
print(a2)
# create horizontal stack
a3 = hstack((a1, a2)) #this adds columns with each other
print(a3)
print(a3.shape)

[list([3, 8, 9, 1]) list([1, 2, 3])]
[list([7, 5, 6, 1]) list([1, 5, 6])]
[list([3, 8, 9, 1]) list([1, 2, 3]) list([7, 5, 6, 1]) list([1, 5, 6])]
(4,)


<ipython-input-17-bcf585d3b72a>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = array([[3,8,9,1],[1,2,3]])
<ipython-input-17-bcf585d3b72a>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = array([[7,5,6,1],[1,5,6]])


In [ ]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2)) # this function adds column
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


#index slice and reshape NUMPY array



##one dimensional list to array

In [ ]:
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55, 66, 77]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55 66 77]
<class 'numpy.ndarray'>


## Two-Dimensional List of Lists to Array

In [ ]:
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66],
[77,88]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]
 [77 88]]
<class 'numpy.ndarray'>


## array indexing 
##one dimensional indexing

In [ ]:
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55, 66, 77])
# index data 
print(data[0])
print(data[5])

11
66


In [ ]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55, 66])
# index data
# print(data[7]) # running this give index error. can try it by  uncommenting the code

IndexError: ignored

In [ ]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55,66])
# index data
print(data[-2])
print(data[-5])

55
22


##two dimensional indexing

In [ ]:
# index two-dimensional array
from numpy import array
# doing data[0,0] and data [0][0] are two different things
data = array([
[11, 22],
[33, 44],
[55, 66]])

print(data[0,0])
print(data[0],[0]) #it gives two different list 1st row and seperate 0 column

11
[11 22] [0]


In [ ]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])

[11 22]


##Array slicing
## one dimensional slicing

In [ ]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [ ]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [ ]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


##Two-Dimensional Slicing

In [ ]:
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]
